image:
  repository: docmarr/kubernetes-multicooker
  tag: "1.0.3"
  pullPolicy: Always 

nameOverride: ""
fullnameOverride: ""

taintThreshold: 25
evictThreshold: 60
evictBackoff: 2.12m
metricsPort: 8080
useAverage: true
targetMetric: 2

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podMonitor:
  enabled: true
  endpoint: "/metrics"
  interval: 30s
  scrapeTimeout: 10s
  namespace: monitoring
  additionalLabels:
    release: "kube-prometheus-stack"
  relabelings:
     - sourceLabels: [__meta_kubernetes_pod_node_name]
       separator: ;
       targetLabel: instance
       replacement: $1
       action: replace